spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/baskin
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl