name: Build Spring Boot Project

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-24.04  # GitHub Actions runner with Ubuntu 24.04

    steps:
    - name: After Finish Pull Request Merged 
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME}}
        password: ${{ secrets.REMOTE_PASSWORD }}
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script_stop: true
        script: |
          pwd

